server:
  port: 9001


spring:
  application:
    name: nacos-sentinel-payment
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    #基础的sentinel配置
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8179




management:
  endpoints:
    web:
      exposure:
        include: '*'