server:
  port: 3344

spring:
  application:
    name: bus-config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/xukkkeee/springcloudProject.git
          search-paths: /
          label: master
          username: guest
          password: guest

eureka:
  client:
    fetch-registy: true
    register-with-eureka: true # 表示是否将自己注册进 EurekaServer 默认为true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/