server:
  port: 85

spring:
  application:
    name: cloud-order-service
    zipkin:
      base-url: http://localhost:9411  # zipkin 地址
    sleuth:
      sampler:
    # 采样率值 介于0-1之间 ，1表示全部采集
      probability: 1



eureka:
  client:
    # 注册进 Eureka 的服务中心
    register-with-eureka: true
    # 检索服务中心的其它服务
    # 单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
